In [2]:
import pandas as pd
import mysql.connector as connector
from pypika import Table, Query

In [3]:
db_connector = connector.connect(
                    host="localhost",
                    user="root",
                    passwd="",
                    database="nest-bot"
                )

In [26]:
df_ols = pd.read_csv('OLS.csv',delimiter=";")
df_ols.dropna(inplace=True)
df_ols

,No,Serial Number,Jenis Barang,Merk Barang,Nama Product,Posisi,Position Name,Group Fungsi
0,1.0,161011188,OPTICAL LIGHT SOURCE,JOINWIT FROM SANFIX,OPTICAL LIGHT SOURCE JOINWIT STANDARD,BRIYAN PRASETYO,Team Leader Maintenance & QE,QE & GAMAS
1,2.0,161011248,OPTICAL LIGHT SOURCE,JOINWIT FROM SANFIX,OPTICAL LIGHT SOURCE JOINWIT STANDARD,SOFYAN NAURI,Teknisi Provisioning Sektor Pasuruan,PROVISIONING
2,3.0,170525270,OPTICAL LIGHT SOURCE,JOINWIT FROM SANFIX,OPTICAL LIGHT SOURCE JOINWIT STANDARD,MUKHAMAD ASRORI,Teknisi I-OAN Sektor Pasuruan,I-OAN
3,4.0,170525288,OPTICAL LIGHT SOURCE,JOINWIT FROM SANFIX,OPTICAL LIGHT SOURCE JOINWIT STANDARD,WAHYU INDRA CHRISTIAN,Teknisi I-OAN Sektor Probolinggo 2,I-OAN
4,5.0,170525300,OPTICAL LIGHT SOURCE,JOINWIT FROM SANFIX,OPTICAL LIGHT SOURCE JOINWIT STANDARD,JIHAD AMIRUL HAQ,Team Leader I-OAN Sektor Pasuruan 2,I-OAN
...,...,...,...,...,...,...,...,...
58,59.0,LS-8352,OPTICAL LIGHT SOURCE,Stintrument,OLS STINTRUMENT [STANDARD],GILANG RAMADHAN AGUNG GUMELAR,Teknisi TSEL,I-OAN
59,60.0,LS-8468,OPTICAL LIGHT SOURCE,Stintrument,OLS STINTRUMENT [STANDARD],ANGGRIAWAN ATMY PUTRA,Team Leader Provisioning & Migrasi Sektor Bangil,PROVISIONING
60,61.0,LS-975,OPTICAL LIGHT SOURCE,Stintrument,OLS STINTRUMENT [STANDARD],MUKLAS ANDIKA WIJAYA,Team Leader I-OAN Sektor Probolinggo 2,I-OAN
61,62.0,LS-988,OPTICAL LIGHT SOURCE,Stintrument,OLS STINTRUMENT [STANDARD],EKO WIDIANTO,Teknisi I-OAN Sektor Probolinggo,I-OAN
62,63.0,LS-990,OPTICAL LIGHT SOURCE,Stintrument,OLS STINTRUMENT [STANDARD],TIGO DWI ANGGA,Teknisi I-OAN Sektor Probolinggo,I-OAN

In [27]:
df_opm = pd.read_csv('OPM.csv',delimiter=";")
df_opm.dropna(inplace=True)
df_opm

,No,Serial Number,Jenis Barang,Merk Barang,Nama Product,Posisi,Position Name,Group Fungsi
0,1.0,1503201128,OPTICAL POWER METER,B&D TECHNOLOGY,OPTICAL POWER METER B&D TECHNOLOGY BD-503,AHMAD ZAINUL IRFAN,Team Leader TSEL & OLO Service,I-OAN
1,2.0,1503201133,OPTICAL POWER METER,B&D TECHNOLOGY,OPTICAL POWER METER B&D TECHNOLOGY BD-503,RUSTAMI HERDI TRIAWAN,Teknisi BGES Service,I-OAN
2,3.0,1503201153,OPTICAL POWER METER,B&D TECHNOLOGY,OPTICAL POWER METER B&D TECHNOLOGY BD-503,ANDY SISWANTO,Site Manager Operation Consumer Service Pasuru...,I-OAN
3,4.0,1503201156,OPTICAL POWER METER,B&D TECHNOLOGY,OPTICAL POWER METER B&D TECHNOLOGY BD-503,ANDY SISWANTO,Site Manager Operation Consumer Service Pasuru...,I-OAN
4,5.0,1503301375,OPTICAL POWER METER,B&D TECHNOLOGY,OPTICAL POWER METER B&D TECHNOLOGY BD-503,ANDY SISWANTO,Site Manager Operation Consumer Service Pasuru...,I-OAN
...,...,...,...,...,...,...,...,...
83,84.0,Opm-5718,OPTICAL POWER METER,Stintrument,OPTICAL POWER METER STINTRUMENT [STANDARD],ANGGRIAWAN ATMY PUTRA,Team Leader Provisioning & Migrasi Sektor Bangil,PROVISIONING
84,85.0,OPM-6167,OPTICAL POWER METER,Stintrument,OPTICAL POWER METER STINTRUMENT [STANDARD],GALI SETIYAWAN,Site Manager CCAN & WAN,I-OAN
85,86.0,opm-6179,OPTICAL POWER METER,Stintrument,OPTICAL POWER METER STINTRUMENT [STANDARD],JIHAD AMIRUL HAQ,Team Leader I-OAN Sektor Pasuruan 2,I-OAN
86,87.0,OPM-6321,OPTICAL POWER METER,Stintrument,OPTICAL POWER METER STINTRUMENT [STANDARD],MUCHAMAD DIDIK SUWARDOYO,Teknisi TSEL,I-OAN
87,88.0,OPM-6713,OPTICAL POWER METER,Stintrument,OPTICAL POWER METER STINTRUMENT [STANDARD],MUHAMMAD IKHYAK GALI OKTANDA,Teknisi I-OAN Sektor Pasuruan 2,I-OAN

In [31]:
df_opm['Serial Number'] = df_opm['Serial Number'].apply(lambda x: str(x).upper())
df_opm['Jenis Barang'] = df_opm['Jenis Barang'].apply(lambda x: str(x).upper())
df_opm['Merk Barang'] = df_opm['Merk Barang'].apply(lambda x: str(x).upper())
df_opm['Nama Product'] = df_opm['Nama Product'].apply(lambda x: str(x).upper())
df_opm['Posisi'] = df_opm['Posisi'].apply(lambda x: str(x).upper())
df_opm.head()

,No,Serial Number,Jenis Barang,Merk Barang,Nama Product,Posisi,Position Name,Group Fungsi
0,1.0,1503201128,OPTICAL POWER METER,B&D TECHNOLOGY,OPTICAL POWER METER B&D TECHNOLOGY BD-503,AHMAD ZAINUL IRFAN,Team Leader TSEL & OLO Service,I-OAN
1,2.0,1503201133,OPTICAL POWER METER,B&D TECHNOLOGY,OPTICAL POWER METER B&D TECHNOLOGY BD-503,RUSTAMI HERDI TRIAWAN,Teknisi BGES Service,I-OAN
2,3.0,1503201153,OPTICAL POWER METER,B&D TECHNOLOGY,OPTICAL POWER METER B&D TECHNOLOGY BD-503,ANDY SISWANTO,Site Manager Operation Consumer Service Pasuru...,I-OAN
3,4.0,1503201156,OPTICAL POWER METER,B&D TECHNOLOGY,OPTICAL POWER METER B&D TECHNOLOGY BD-503,ANDY SISWANTO,Site Manager Operation Consumer Service Pasuru...,I-OAN
4,5.0,1503301375,OPTICAL POWER METER,B&D TECHNOLOGY,OPTICAL POWER METER B&D TECHNOLOGY BD-503,ANDY SISWANTO,Site Manager Operation Consumer Service Pasuru...,I-OAN

In [32]:
df_ols['Serial Number'] = df_ols['Serial Number'].apply(lambda x: str(x).upper())
df_ols['Jenis Barang'] = df_ols['Jenis Barang'].apply(lambda x: str(x).upper())
df_ols['Merk Barang'] = df_ols['Merk Barang'].apply(lambda x: str(x).upper())
df_ols['Nama Product'] = df_ols['Nama Product'].apply(lambda x: str(x).upper())
df_ols['Posisi'] = df_ols['Posisi'].apply(lambda x: str(x).upper())
df_ols.head()

,No,Serial Number,Jenis Barang,Merk Barang,Nama Product,Posisi,Position Name,Group Fungsi
0,1.0,161011188,OPTICAL LIGHT SOURCE,JOINWIT FROM SANFIX,OPTICAL LIGHT SOURCE JOINWIT STANDARD,BRIYAN PRASETYO,Team Leader Maintenance & QE,QE & GAMAS
1,2.0,161011248,OPTICAL LIGHT SOURCE,JOINWIT FROM SANFIX,OPTICAL LIGHT SOURCE JOINWIT STANDARD,SOFYAN NAURI,Teknisi Provisioning Sektor Pasuruan,PROVISIONING
2,3.0,170525270,OPTICAL LIGHT SOURCE,JOINWIT FROM SANFIX,OPTICAL LIGHT SOURCE JOINWIT STANDARD,MUKHAMAD ASRORI,Teknisi I-OAN Sektor Pasuruan,I-OAN
3,4.0,170525288,OPTICAL LIGHT SOURCE,JOINWIT FROM SANFIX,OPTICAL LIGHT SOURCE JOINWIT STANDARD,WAHYU INDRA CHRISTIAN,Teknisi I-OAN Sektor Probolinggo 2,I-OAN
4,5.0,170525300,OPTICAL LIGHT SOURCE,JOINWIT FROM SANFIX,OPTICAL LIGHT SOURCE JOINWIT STANDARD,JIHAD AMIRUL HAQ,Team Leader I-OAN Sektor Pasuruan 2,I-OAN